[package]
authors = ["Edward Yang <edward.yang6771@gmail.com>"]
build = "build.rs"
links = "topsdk"
name = "top-sdk"
version = "0.1.0"

[build-dependencies]
gcc = "0.3"

[dependencies]
curl-sys = "0.3.6"
quick-error = "1.1.0"
